// <auto-generated />
namespace Cec.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _005_AddedAreaRequireStatusId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_005_AddedAreaRequireStatusId));
        
        string IMigrationMetadata.Id
        {
            get { return "201503160436171__005_AddedAreaRequireStatusId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
